SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

FPS = 60
MAX_SECONDS = 16
SPRITE_SAMPLE_LIMIT = 10  # Maximum number of sprites to log per group

PLAYER_RADIUS = 20
LINE_WIDTH = 2

PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500

PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3


PLAYER_ACCELERATION = 500
PLAYER_FRICTION = 0.99


ASTEROID_LARGE_SCORE = 20
ASTEROID_MEDIUM_SCORE = 50
ASTEROID_SMALL_SCORE = 100


PLAYER_STARTING_LIVES = 3
PLAYER_RESPAWN_INVULNERABILITY = 2.0